export const keys = process => {
    return new Map([
        ["Digit0","0"],
        ["Digit1","1"],
        ["Digit2","2"],
        ["Digit3","3"],
        ["Digit4","4"],
        ["Digit5","5"],
        ["Digit6","6"],
        ["Digit7","7"],
        ["Digit8","8"],
        ["Digit9","9"],
        ["Numpad0",process === "ps" ? "0" : "Num0"],
        ["Numpad1",process === "ps" ? "1" : "Num1"],
        ["Numpad2",process === "ps" ? "2" : "Num2"],
        ["Numpad3",process === "ps" ? "3" : "Num3"],
        ["Numpad4",process === "ps" ? "4" : "Num4"],
        ["Numpad5",process === "ps" ? "5" : "Num5"],
        ["Numpad6",process === "ps" ? "6" : "Num6"],
        ["Numpad7",process === "ps" ? "7" : "Num7"],
        ["Numpad8",process === "ps" ? "8" : "Num8"],
        ["Numpad9",process === "ps" ? "9" : "Num9"],
        ["NumpadEnter",process === "ps" ? ["{ENTER}","enter"] : "NumEnter"],
        ["KeyA","a"],
        ["KeyB","b"],
        ["KeyC","c"],
        ["KeyD","d"],
        ["KeyE","e"],
        ["KeyF","f"],
        ["KeyG","g"],
        ["KeyH","h"],
        ["KeyI","i"],
        ["KeyJ","j"],
        ["KeyK","k"],
        ["KeyL","l"],
        ["KeyM","m"],
        ["KeyN","n"],
        ["KeyO","o"],
        ["KeyP","p"],
        ["KeyQ","q"],
        ["KeyR","r"],
        ["KeyS","s"],
        ["KeyT","t"],
        ["KeyU","u"],
        ["KeyV","v"],
        ["KeyW","w"],
        ["KeyX","x"],
        ["KeyY","y"],
        ["KeyZ","z"],
        ["F1",process === "ps" ? "{F1}" : "F1"],
        ["F2",process === "ps" ? "{F2}" : "F2"],
        ["F3",process === "ps" ? "{F3}" : "F3"],
        ["F4",process === "ps" ? "{F4}" : "F4"],
        ["F5",process === "ps" ? "{F5}" : "F5"],
        ["F6",process === "ps" ? "{F6}" : "F6"],
        ["F7",process === "ps" ? "{F7}" : "F7"],
        ["F8",process === "ps" ? "{F8}" : "F8"],
        ["F9",process === "ps" ? "{F9}" : "F9"],
        ["F10",process === "ps" ? "{F10}" : "F10"],
        ["F11",process === "ps" ? "{F11}" : "F11"],
        ["F12",process === "ps" ? "{F12}" : "F12"],
        ["NumpadMultiply",process === "ps" ? ["{MULTIPLY}","*"] : "NumMultiply"],
        ["NumpadAdd",process === "ps" ? ["{ADD}","+"] : "NumAdd"],
        ["NumpadSubtract",process === "ps" ? ["{SUBTRACT}","-"] : "NumSubtract"],
        ["NumpadDivide",process === "ps" ? ["{DIVIDE}","/"] : "NumDivide"],
        ["NumpadDecimal",process === "ps" ? "." : "NumDecimal"],
        ["Minus","-"],
        ["Equal","="],
        ["BracketLeft","["],
        ["BracketRight","]"],
        ["Backslash","#"],
        ["IntlBackslash","\\"],
        ["Semicolon",";"],
        ["Quote","\'"],
        ["Comma",","],
        ["Period","."],
        ["Slash","/"],
        ["Backspace",process === "ps" ? ["{BACKSPACE}","backsp"] : "Backspace"],
        ["Pause",process === "ps" ? "{BREAK}" : "Pause"],
        ["Tab",process === "ps" ? "{TAB}" : "Tab"],
        ["Enter",process === "ps" ? "{ENTER}" : "Enter"],
        ["Escape",process === "ps" ? ["{ESC}","esc"] : "Esc"],
        ["Delete",process === "ps" ? ["{DELETE}","del"] : "Delete"],
        ["Insert",process === "ps" ? ["{INSERT}","ins"] : "Insert"],
        ["Home",process === "ps" ? "{HOME}" : "Home"],
        ["End",process === "ps" ? "{END}" : "End"],
        ["PageUp",process === "ps" ? ["{PGUP}","pgup"] : "PageUp"],
        ["PageDown",process === "ps" ? ["{PGDN}","pgdn"] : "PageDown"],
        ["ArrowUp",process === "ps" ? ["{UP}","up"] : "ArrowUp"],
        ["ArrowDown",process === "ps" ? ["{DOWN}","down"] : "ArrowDown"],
        ["ArrowLeft",process === "ps" ? ["{LEFT}","left"] : "ArrowLeft"],
        ["ArrowRight",process === "ps" ? ["{RIGHT}","right"] : "ArrowRight"],
        ["CapsLock",process === "ps" ? ["{CAPSLOCK}","caps"] : "CapsLock"],
        ["ScrollLock",process === "ps" ? ["{SCROLLLOCK}","scrlock"] : "ScrollLock"],
        ["NumLock",process === "ps" ? "{NUMLOCK}" : "NumLock"],
        ["Space",process === "ps" ? [" ","space"] : "Space"],
        ["ShiftLeft",process === "ps" ? null : "Shift"],
        ["ShiftRight",process === "ps" ? null : "Shift"],
        ["ControlLeft",process === "ps" ? null : "Ctrl"],
        ["ControlRight",process === "ps" ? null : "Ctrl"],
        ["AltLeft",process === "ps" ? null : "Alt"],
        ["AltRight",process === "ps" ? null : "Alt"],
        ["MetaLeft",process === "ps" ? null : "Super"],
        ["MetaRight",process === "ps" ? null : "Super"],
        ["Backquote",process === "ps" ? null : "Backquote"]
    ])
}